### ISSUE TITLE
Migration from the JdeRobot/JdeRobot repository

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/VisualStates#1]
VisualStates will have now its own standalone repository. This will make easier to generate a ROS package for it, the development of this tool and the creation of an AppImage of it.
Right now the source code of the tool and its examples are inside the JdeRobot/JdeRobot repository. 

Beyond copying the source code here, a CMake configuration file must be prepared, including dependences of the code, so this tool can be installed in the right directories.

**Comment by okanasik** [comment]
Dear @jmplaza,
I created a separate folder for visualstates, but I do not have permission to push here. Will you give me permission? or Do I need to create a pull request. Best.

**Comment by jmplaza** [comment]
Sure @okanasik, done, you can push now. Anyway maybe it is a better policy to create a pull request and then you can merge it yourself. This way all the changes go through the issue + pull_request mechanism. It is a better policy in the long run. It makes easier to track the development and the double check by other developer before merging. Let's follow it, please.

**Comment by okanasik** [comment]
Dear @jmplaza, as suggested I created a pull request.
