### ISSUE TITLE
Check if inputs to lists were previously added.

### ISSUE THREAD

**Issue by sudo-panda** [JdeRobot/VisualStates#119]
This check is required in:

- [x] Libraries

- [x] Topics (ROS Config)

- [x] Packages (ROS Config)

- [x] Workspaces (ROS Config)

**Comment by sudo-panda** [comment]
These lists individually require different checks which must be decided before solving the issue.

**Comment by sudo-panda** [comment]
I would like to work on this issue

**Comment by okanasik** [comment]
fixed by #129
