### ISSUE TITLE
VisualStates Release for ROS Melodic

### ISSUE THREAD

**Issue by jiban-jyoti** [JdeRobot/VisualStates#146]
What is the release date for VisualStates package for ROS-melodic as currently I am doing source installaton to run the exercises based on VisualStates. Also well done for maintaining this package and I am excited to know the release dates.

**Comment by okanasik** [comment]
Thank you for your interest in the project. We are ready for the release, we are planning to make the release in the following week. I will let you know when we release. If you encounter any issues please do not hesitate to report.

**Comment by jiban-jyoti** [comment]
Hello @okanasik I think the visualstates package for ROS-melodic is released now. Can you tell me the instructions to install it. I tried source installation but I am getting errors.

rosrun visualstates main.py
Traceback (most recent call last):
  File "/home/jiban/catkin_ws/src/VisualStates/scripts/main.py", line 25, in <module>
    from visualstates.gui.visualstates import VisualStates
ImportError: No module named visualstates.gui.visualstates

**Comment by okanasik** [comment]
Hi @jiban-jyoti , I checked the problem. If you rename the directory to all lowercase letters, it should work. Did you solve the problem?

**Comment by jiban-jyoti** [comment]
Yes Sir, It is working perfectly now. We should update the commands also.

**Comment by jiban-jyoti** [comment]
Yes Sir, It is working perfectly now. We should update the commands also.
