### ISSUE TITLE
The TurtleBot tutorial should be self-contained

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/VisualStates#16]
The VisualStates repository should include the worlds, models, etc which are used in [the tutorial](https://jderobot.org/Tutorials#TurtleBot_Example_with_ROS) but are not directly available from ROS packages. For instance the [Gazebo world](https://github.com/JdeRobot/JdeRobot/blob/master/src/drivers/gazeboserver/worlds/kobuki-simple-ros.world). Somewhere inside the examples directory seems a good place for them.

**Comment by okanasik** [comment]
The examples in examples directory has installation directives. The user needs to install kobuki ros packages and jderobot gazebo assets.
