### ISSUE TITLE
[BUG] Remove state option does not update TreeModel

### ISSUE THREAD

**Issue by pushkalkatara** [JdeRobot/VisualStates#17]
While removing a state from automata scene by, the state disappears from the automata scene but not from the tree model.

**Comment by okanasik** [comment]
Dear @pushkalkatara, can you also write the steps to reproduce this error. I am not able to reproduce while creating a automata. Best,

**Comment by pushkalkatara** [comment]
Respected Sir,
When removing a substate of a state, the state gets removed from the automata scene but not from the TreeView like in the case below.
![err2](https://user-images.githubusercontent.com/21266230/40712538-98a61844-641b-11e8-838e-0ac335a7459a.png)
![err 3](https://user-images.githubusercontent.com/21266230/40712693-ec81be78-641b-11e8-9635-a42d9c6911b4.png)


But in the case when a state is removed from the root state, the TreeView is also updated like in the case below.
![err1](https://user-images.githubusercontent.com/21266230/40712539-992b9e7e-641b-11e8-9765-13ea19832993.png)
