### ISSUE TITLE
Notifying connection to interfaces

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/VisualStates#4]
When using a behavior generated by Visual States, the behavior node always prints that it is connected to the interfaces, even when it is not.

This has been checked out using Python components and ROS drivers with JdeRobot Comm.

(this issue comes from [here](https://github.com/JdeRobot/JdeRobot/issues/1077), where the VisualStates code was until this week)

**Comment by okanasik** [comment]
Since, visualstates do not use JdeRobot Comm interface, that bug is not relevant anymore.
