### ISSUE TITLE
Edit config files

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/VisualStates#5]
Now, when creating the configuration file using Visual States it is possible to add a new interface or to remove an existing one. It would be useful to edit the existing interfaces also, allowing to modify their fields and save them. Right now, the only way to do this is to create a new interface with the desired fields and remove the old one.

(this issue comes from [here](https://github.com/JdeRobot/JdeRobot/issues/1076), where the VisualStates code was until this week)

Watchout this change @pushkalkatara

**Comment by pushkalkatara** [comment]
Thanks for the link. I would be following this repository from now for VisualStates.

**Comment by pushkalkatara** [comment]
Editing topic name is now working with this implementation - https://github.com/JdeRobot/VisualStates/pull/24/commits/a1076e65f952be5fe95aa0767a83e54f3201f256
