### ISSUE TITLE
Access to interfaces inside time transitions

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/VisualStates#6]
With the current state of the tool, time transitions do not have access to the interfaces object. This would be useful because it is possible to execute code when the transition is activated, and the interfaces object has variables that are common to the rest of the automaton, so with this modification the time transitions will be able to modify these variables when they got activated.

(this issue comes from [here](https://github.com/JdeRobot/JdeRobot/issues/1064), where the VisualStates code was until this week)

**Comment by okanasik** [comment]
Since there is a new duplicate issue #86 , I close this issue.
