### ISSUE TITLE
Example BumpAndGo is dependent on Gazebo 9.

### ISSUE THREAD

**Issue by pushkalkatara** [JdeRobot/VisualStates#66]
As package kobuki_gazebo depends on gazebo 7, the example needs Gazebo 7 installed instead of Gazebo 9

**Comment by pushkalkatara** [comment]
I noticed the changes to original package [kobuki_desktop](https://github.com/yujinrobot/kobuki_desktop/tree/devel/kobuki_gazebo_plugins) supports Gazebo 9

**Comment by okanasik** [comment]
We have moved visualstates examples to https://github.com/JdeRobot/VisualStates-examples
