### ISSUE TITLE
Example PriusCarDemo ROS-Gazebo packages

### ISSUE THREAD

**Issue by pushkalkatara** [JdeRobot/VisualStates#67]
Ported [car_demo](https://github.com/osrf/car_demo) Nvidia docker to [prius_gazebo](https://github.com/pushkalkatara/prius_gazebo) seperate package. Also added support for Gazebo 9.
Working on demo with VisualStates

**Comment by pushkalkatara** [comment]
I developed the example with the latest update of VisualStates but while running the example, the RunTime GUI is displaying all the states on the same level, but the example is executing successfully.
@okanasik Please suggest resolution to the issue.

Steps to reproduce the issue - 
1. Clone [prius_gazebo](https://github.com/pushkalkatara/prius_gazebo/tree/visualstates) with VisualStates branch.
2. compile the repository using catkin_make
3. source devel/setup.bash
4. roslaunch prius_gazebo prius_world.launch
5. rosrun prius_spawn prius_spawn.py --displaygui=true

![states](https://user-images.githubusercontent.com/21266230/47782050-48d13a00-dd25-11e8-879e-f440e44b15b2.png)

**Comment by okanasik** [comment]
fixed by #72
