### ISSUE TITLE
CMake configure file creates files in build directory and created python file cannot be installed

### ISSUE THREAD

**Issue by jmplaza** [JdeRobot/VisualStates#7]
CMake configure file creates files in build directory and created python file cannot be installed. We should install the file relative to the CMAKE_CURRENT_BINARY_DIR directory.

(this issue comes from [here](https://github.com/JdeRobot/JdeRobot/issues/906), where the VisualStates code was until this week)

**Comment by okanasik** [comment]
This is already solved with the latest change on the CMakeLists file
