### ISSUE TITLE
Interface to select states to import

### ISSUE THREAD

**Issue by pushkalkatara** [JdeRobot/VisualStates#91]
Currently, using Import functionality, all the states are imported in the developing behavior. In some cases, only some of the selected states are required, hence an interface which display all the states and provides functionality to select one or all states to be imported.

**Comment by sudo-panda** [comment]
I would like to work on adding this feature.

**Comment by sudo-panda** [comment]
Does the interface show the visual of transitions with the states or only the state names?

**Comment by pushkalkatara** [comment]
Hi, @sudo-panda Thanks for approaching the issue, we can start initially just with displaying the states.

**Comment by sudo-panda** [comment]
Are the state ids always continuous or can there be gaps and do the child states have to have greater state ids than the ones in the upper level?

**Comment by pushkalkatara** [comment]
Hi @sudo-panda , the child states need not be continuous, also it's not necessary that the child state would have greater state ids compared to the ones in the upper level. The whole procedure works on recursive parsing.

**Comment by sudo-panda** [comment]
Shouldn't a deleted state delete a destination Transitions along with Origin Transition both during  importing and in the main VisualStates window. Right now it only deletes origin Transitions.

**Comment by pushkalkatara** [comment]
I didn't get you, what do you mean by origin transition or destination
transition? I believe a transition points from origin state to a
destination state. If we remove a particular state, all the transitions
attached to it are automatically removed. But if a transition is removed,
both the states connected to it stays in the automata.

**Comment by sudo-panda** [comment]
That should be the ideal behaviour but right now only the transitions that originate from a state are removed on removal of the state and not the ones that point towards the state

**Comment by sudo-panda** [comment]
Should I modify the current behaviour?

**Comment by sudo-panda** [comment]
@pushkalkatara could you please reply so that finish adding this feature.

**Comment by pushkalkatara** [comment]
Hi @sudo-panda . I was busy with something. I think we would require more discussion over this, it would be better to create a separate issue for it.

**Comment by sudo-panda** [comment]
No problem. Should I create a pull request to add this feature or first solve that issue?

**Comment by pushkalkatara** [comment]
Both are unrelated, you can proceed with any of them.

**Comment by pushkalkatara** [comment]
Developing as part of GSoC 2k19 at https://github.com/TheRoboticsClub/colab-gsoc2019-Baidyanath_Kundu/pulls hence closing the issue.
