### ISSUE TITLE
New visualstate behavior should clear the last file path from filemanager

### ISSUE THREAD

**Issue by okanasik** [JdeRobot/VisualStates#93]
When we first open a visualstates behavior, then we choose to create a new visualstates behavior, but the filemanager still keeps the filename of the previously opened behavior. Therefore, when the user clicks the save button, the new behavior will override the previously opened behavior.

**Comment by sudo-panda** [comment]
I would like to work on this issue.
Do I just need to set filemanager.fullPath to empty when it is opening a new file or am I going about it wrong again?

**Comment by okanasik** [comment]
Yes, it could be fine to set it to empty, but you should also check whether the empty filename is checked when user wants to save the file. In that case, file save dialog should open since the there is no filename for the current behavior.
Another important issue about the filemanager is that since behavior import also uses the filemanager, it temporarily sets a filename during the import, but as the import ends, it should reset the previous value of the filemanager file path.
Can you check these two cases?

**Comment by sudo-panda** [comment]
Ok I will look into these cases.

**Comment by sudo-panda** [comment]
In the case of import behavior, it doesn't set the path permanently so it isn't a problem.

**Comment by sudo-panda** [comment]
I have solved to issue but will send a pull request later will more solved issues.

**Comment by okanasik** [comment]
Solved by #106
